version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./nodemon.json
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"